import type { Express } from "express";

import route1 from "./routes/agent";
import route2 from "./routes/agent/answer";
import route3 from "./routes/agent/canvasResult";
import route4 from "./routes/agent/create";
import route5 from "./routes/agent/get";
import route6 from "./routes/agent/list";
import route7 from "./routes/agent/mentionSource";
import route8 from "./routes/agent/message";
import route9 from "./routes/agent/rename";
import route10 from "./routes/agent/skills";
import route11 from "./routes/agents/a2a/get";
import route12 from "./routes/agents/a2a/save";
import route13 from "./routes/agents/connect";
import route14 from "./routes/agents/get";
import route15 from "./routes/agents/install";
import route16 from "./routes/agents/read";
import route17 from "./routes/agents/save";
import route18 from "./routes/agents/setEnabled";
import route19 from "./routes/agents/uninstall";
import route20 from "./routes/ai/generate";
import route21 from "./routes/ai/media/generate";
import route22 from "./routes/ai/media/models";
import route23 from "./routes/ai/media/task";
import route24 from "./routes/ai/media/taskCancel";
import route25 from "./routes/ai/media/taskStatus";
import route26 from "./routes/ai/models";
import route27 from "./routes/assets/list";
import route28 from "./routes/assets/mkdir";
import route29 from "./routes/assets/read";
import route30 from "./routes/assets/remove";
import route31 from "./routes/assets/rename";
import route32 from "./routes/assets/save";
import route33 from "./routes/desktop/clipboard/read";
import route34 from "./routes/desktop/clipboard/write";
import route35 from "./routes/desktop/devtools";
import route36 from "./routes/desktop/openUrl";
import route37 from "./routes/desktop/plugins/install";
import route38 from "./routes/desktop/providerFile/read";
import route39 from "./routes/desktop/providerFile/select";
import route40 from "./routes/desktop/ready";
import route41 from "./routes/desktop/saveFile";
import route42 from "./routes/desktop/selectDirectory";
import route43 from "./routes/desktop/selectSaveFile";
import route44 from "./routes/desktop/update/apply";
import route45 from "./routes/desktop/update/check";
import route46 from "./routes/desktop/update/download";
import route47 from "./routes/desktop/update/index";
import route48 from "./routes/ext/install";
import route49 from "./routes/ext/list";
import route50 from "./routes/ext/read";
import route51 from "./routes/ext/save";
import route52 from "./routes/ext/setEnabled";
import route53 from "./routes/ext/uninstall";
import route54 from "./routes/ffmpeg/cancel";
import route55 from "./routes/ffmpeg/download";
import route56 from "./routes/ffmpeg/events";
import route57 from "./routes/ffmpeg/execute";
import route58 from "./routes/ffmpeg/progress";
import route59 from "./routes/ffmpeg/status";
import route60 from "./routes/mcp/control/events";
import route61 from "./routes/mcp/control/result";
import route62 from "./routes/mcp/control/state";
import route63 from "./routes/mcp/skill";
import route64 from "./routes/mcp/status";
import route65 from "./routes/nodes/files";
import route66 from "./routes/nodes/get";
import route67 from "./routes/nodes/install";
import route68 from "./routes/nodes/save";
import route69 from "./routes/nodes/setEnabled";
import route70 from "./routes/nodes/uninstall";
import route71 from "./routes/plugins/export";
import route72 from "./routes/production/export";
import route73 from "./routes/production/shots/get";
import route74 from "./routes/production/shots/save";
import route75 from "./routes/production/shots/update";
import route76 from "./routes/providers/debug/inspect";
import route77 from "./routes/providers/debug/run";
import route78 from "./routes/providers/media/add";
import route79 from "./routes/providers/media/delete";
import route80 from "./routes/providers/media/health";
import route81 from "./routes/providers/media/list";
import route82 from "./routes/providers/media/models";
import route83 from "./routes/providers/media/save";
import route84 from "./routes/providers/models";
import route85 from "./routes/settings/get";
import route86 from "./routes/settings/personalization/get";
import route87 from "./routes/settings/personalization/save";
import route88 from "./routes/settings/save";
import route89 from "./routes/settings/systemPrompt";
import route90 from "./routes/skills/create";
import route91 from "./routes/skills/get";
import route92 from "./routes/skills/install";
import route93 from "./routes/skills/list";
import route94 from "./routes/skills/move";
import route95 from "./routes/skills/order";
import route96 from "./routes/skills/read";
import route97 from "./routes/skills/save";
import route98 from "./routes/skills/uninstall";
import route99 from "./routes/tools/client";
import route100 from "./routes/tools/get";
import route101 from "./routes/tools/install";
import route102 from "./routes/tools/renderers";
import route103 from "./routes/tools/save";
import route104 from "./routes/tools/setEnabled";
import route105 from "./routes/tools/uninstall";
import route106 from "./routes/workspaces/check";
import route107 from "./routes/workspaces/files/copy";
import route108 from "./routes/workspaces/files/list";
import route109 from "./routes/workspaces/files/mkdir";
import route110 from "./routes/workspaces/files/read";
import route111 from "./routes/workspaces/files/remove";
import route112 from "./routes/workspaces/files/rename";
import route113 from "./routes/workspaces/files/reveal";
import route114 from "./routes/workspaces/files/write";
import route115 from "./routes/workspaces/list";
import route116 from "./routes/workspaces/selectDirectory";

export default (app: Express) => {
  app.use("/api/agent", route1);
  app.use("/api/agent/answer", route2);
  app.use("/api/agent/canvasResult", route3);
  app.use("/api/agent/create", route4);
  app.use("/api/agent/get", route5);
  app.use("/api/agent/list", route6);
  app.use("/api/agent/mentionSource", route7);
  app.use("/api/agent/message", route8);
  app.use("/api/agent/rename", route9);
  app.use("/api/agent/skills", route10);
  app.use("/api/agents/a2a/get", route11);
  app.use("/api/agents/a2a/save", route12);
  app.use("/api/agents/connect", route13);
  app.use("/api/agents/get", route14);
  app.use("/api/agents/install", route15);
  app.use("/api/agents/read", route16);
  app.use("/api/agents/save", route17);
  app.use("/api/agents/setEnabled", route18);
  app.use("/api/agents/uninstall", route19);
  app.use("/api/ai/generate", route20);
  app.use("/api/ai/media/generate", route21);
  app.use("/api/ai/media/models", route22);
  app.use("/api/ai/media/task", route23);
  app.use("/api/ai/media/taskCancel", route24);
  app.use("/api/ai/media/taskStatus", route25);
  app.use("/api/ai/models", route26);
  app.use("/api/assets/list", route27);
  app.use("/api/assets/mkdir", route28);
  app.use("/api/assets/read", route29);
  app.use("/api/assets/remove", route30);
  app.use("/api/assets/rename", route31);
  app.use("/api/assets/save", route32);
  app.use("/api/desktop/clipboard/read", route33);
  app.use("/api/desktop/clipboard/write", route34);
  app.use("/api/desktop/devtools", route35);
  app.use("/api/desktop/openUrl", route36);
  app.use("/api/desktop/plugins/install", route37);
  app.use("/api/desktop/providerFile/read", route38);
  app.use("/api/desktop/providerFile/select", route39);
  app.use("/api/desktop/ready", route40);
  app.use("/api/desktop/saveFile", route41);
  app.use("/api/desktop/selectDirectory", route42);
  app.use("/api/desktop/selectSaveFile", route43);
  app.use("/api/desktop/update/apply", route44);
  app.use("/api/desktop/update/check", route45);
  app.use("/api/desktop/update/download", route46);
  app.use("/api/desktop/update", route47);
  app.use("/api/ext/install", route48);
  app.use("/api/ext/list", route49);
  app.use("/api/ext/read", route50);
  app.use("/api/ext/save", route51);
  app.use("/api/ext/setEnabled", route52);
  app.use("/api/ext/uninstall", route53);
  app.use("/api/ffmpeg/cancel", route54);
  app.use("/api/ffmpeg/download", route55);
  app.use("/api/ffmpeg/events", route56);
  app.use("/api/ffmpeg/execute", route57);
  app.use("/api/ffmpeg/progress", route58);
  app.use("/api/ffmpeg/status", route59);
  app.use("/api/mcp/control/events", route60);
  app.use("/api/mcp/control/result", route61);
  app.use("/api/mcp/control/state", route62);
  app.use("/api/mcp/skill", route63);
  app.use("/api/mcp/status", route64);
  app.use("/api/nodes/files", route65);
  app.use("/api/nodes/get", route66);
  app.use("/api/nodes/install", route67);
  app.use("/api/nodes/save", route68);
  app.use("/api/nodes/setEnabled", route69);
  app.use("/api/nodes/uninstall", route70);
  app.use("/api/plugins/export", route71);
  app.use("/api/production/export", route72);
  app.use("/api/production/shots/get", route73);
  app.use("/api/production/shots/save", route74);
  app.use("/api/production/shots/update", route75);
  app.use("/api/providers/debug/inspect", route76);
  app.use("/api/providers/debug/run", route77);
  app.use("/api/providers/media/add", route78);
  app.use("/api/providers/media/delete", route79);
  app.use("/api/providers/media/health", route80);
  app.use("/api/providers/media/list", route81);
  app.use("/api/providers/media/models", route82);
  app.use("/api/providers/media/save", route83);
  app.use("/api/providers/models", route84);
  app.use("/api/settings/get", route85);
  app.use("/api/settings/personalization/get", route86);
  app.use("/api/settings/personalization/save", route87);
  app.use("/api/settings/save", route88);
  app.use("/api/settings/systemPrompt", route89);
  app.use("/api/skills/create", route90);
  app.use("/api/skills/get", route91);
  app.use("/api/skills/install", route92);
  app.use("/api/skills/list", route93);
  app.use("/api/skills/move", route94);
  app.use("/api/skills/order", route95);
  app.use("/api/skills/read", route96);
  app.use("/api/skills/save", route97);
  app.use("/api/skills/uninstall", route98);
  app.use("/api/tools/client", route99);
  app.use("/api/tools/get", route100);
  app.use("/api/tools/install", route101);
  app.use("/api/tools/renderers", route102);
  app.use("/api/tools/save", route103);
  app.use("/api/tools/setEnabled", route104);
  app.use("/api/tools/uninstall", route105);
  app.use("/api/workspaces/check", route106);
  app.use("/api/workspaces/files/copy", route107);
  app.use("/api/workspaces/files/list", route108);
  app.use("/api/workspaces/files/mkdir", route109);
  app.use("/api/workspaces/files/read", route110);
  app.use("/api/workspaces/files/remove", route111);
  app.use("/api/workspaces/files/rename", route112);
  app.use("/api/workspaces/files/reveal", route113);
  app.use("/api/workspaces/files/write", route114);
  app.use("/api/workspaces/list", route115);
  app.use("/api/workspaces/selectDirectory", route116);
}
